### ISSUE TITLE
Where is the project's JAR?

### ISSUE THREAD

**Issue by rob005** [liquibase/liquibase-groovy-dsl#10]
I apologise if this is the wrong place, but I am trying to find the JAR that is mentioned in the 'usage' section ("Simply include this project's jar file in your class path").

Are you referring to the gradle-wrapper.jar?

**Comment by stevesaliman** [comment]
The documentation might be little vague on this...

To use the Groovy Liquibase DSL, the Groovy DSL classes need to be in the classpath.  How you do this depends on how you are running Liquibase.  

If you are running it from the command line, you'd need to download (or build) the DSL jar and include it on the java command line.  If you're using Maven, you'd need to declare a dependency on the DSL, or use the Liquibase Maven plugin.

Since you mention the gradle-wrapper, I'm guessing you're doing a Gradle build.  The best way to use the Groovy DSL in Gradle is with the [Liquibase Gradle Plugin](https://github.com/liquibase/liquibase-gradle-plugin).  That project's documentation should have everything you need to get started.
