### ISSUE TITLE
Question support for mongo extension

### ISSUE THREAD

**Issue by virtualdogbert** [liquibase/liquibase-groovy-dsl#51]
So I guessing that out of the box using liquibase with the mongo extension:
https://github.com/liquibase/liquibase-mongodb

would not be supported by the DSL correct?

How big of a project would you think it would  be to create support for that?

Thanks I love the project. Using it is very intuitive, coming from experience using the Grails Db Migration plugin.

**Comment by stevesaliman** [comment]
Short answer?  It would be a big effort.

There are two ways to support 3rd party Liquibase extensions.

1. Discover all the new methods and properties that the extension added to Liquibase and add them to the DSL.  And once I start doing this for one, I'll need to start doing it for many.  This would be a nightmare to support.

2. Use the `ParsedNode` solution Liquibase introduced in version 4.  This would involve a complete rewrite of the DSL, but I think it would be a very worthwhile thing to do because we'd be able to support any version of Liquibase and any extension.  However, there is an issue with the way ParsedNodes work.  They silently ignore any property they don't recognize.  This means that if you misspell a property like `tablespaceName` in the `create` change, Liquibase will tell you it did what you asked, even though it didn't.  I'm reluctant to rewrite the DSL until that gets fixed in Liquibase itself.

**Comment by virtualdogbert** [comment]
Fair enough and thanks for responding. I think we found another project for managing changes in mongo, but I no longer work for that company.
