### ISSUE TITLE
Misleading error message if unknown precondition used

### ISSUE THREAD

**Issue by b-gyula** [liquibase/liquibase-groovy-dsl#61]
Error: `Unexpected error running Liquibase: Property 'd' not found on object type org.codehaus.groovy.runtime.NullObject` is logged if unknown precondition used like in the sample below
```groovy
databaseChangeLog {
	preConditions{
		unknown(d:'')
	}
}
```

Error: `databaseChangeLog / preConditions: 'unknown' is an invalid precondition` would be nicer

**Comment by stevesaliman** [comment]
Release 4.0.0 has improved messaging for unknown preconditions.  In your example, it would now say `ChangeSet '<unknown>': 'unknown' is an invalid precondition`

The first "unknown" is because the precondiditon is not inside a changeset, and the second is because that is the name of the precondition you used in your example.
