### ISSUE TITLE
Update the documentation 

### ISSUE THREAD

**Issue by ddimtirov** [liquibase/liquibase-groovy-dsl#9]
http://www.liquibase.org/documentation/other_formats.html 

Says that the Groovy DSL is third party, unaffiliated with Liquibase project and it points to the old repo.

**Comment by stevesaliman** [comment]
Good catch.

I'm not sure of Nathan (the creator of Liquibase) will consider the Groovy DSL (or the Gradle plugin that uses it) to be a "Liquibase developed" project, since it is still maintained outside the Liquibase team, but I think the link in the documentation should still go to the right project.

I created https://liquibase.jira.com/browse/CORE-2639 to request the documentation change.  Since it is not a change to the DSL itself, I'm going to close this issue.

Thanks again for finding this.
